### ISSUE TITLE
Bakingo Cake Service error

### ISSUE THREAD

**Issue by MuskanJain2020** [raghuhhh/Cognizant_Digital_Nurture_2.0-Spring-MVC-and-Spring-Boot-#1]
hey can you please tell me how to solve this error     
Proposed grade: 33.333336 / 100 Result Description 
Fail 1 - Unable to locate element: #name 
Fail 2 - Unable to locate element: #phonenumber 
Fail 3 - Unable to locate element: #address 
Fail 4 - Unable to locate element: #flavor 
Fail 5 - Unable to locate element: *[name='submit'] 
Fail 6 - Unable to locate element: #includecandles 
Fail 7 - Unable to locate element: #includeinscription
 Fail 8 - Unable to locate element: #theinscription
 Fail 9 - Unable to locate element: *[name='form'] 
Fail 10 - Unable to locate element: #name 
Fail 11 - Unable to locate element: #phonenumber 
Fail 12 - Unable to locate element: #selectedcake1 
Fail 13 - Unable to locate element: #flavor
 Fail 14 - Unable to locate element: #name 

Test Case Failed

**Comment by vinay030901** [comment]
I am getting this error too.

**Comment by web-thiru** [comment]
Do you guys solved this now?

**Comment by Ranjith236838** [comment]
did anyone solved this error?
